ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = uno
#BOARD_TAG    = mini328
ARDUINO_PORT = /dev/ttyACM*

#ARDUINO_LIBS = Ethernet Ethernet/utility SPI
ARDUINO_LIBS = SoftwareSerial I2Cmaster
include /usr/share/arduino/Arduino.mk
#ISP_PROG         = -c stk500v1
